name: Fontship
on:
  issues:
    types: [opened]
jobs:
  fontship:
    runs-on: ubuntu-latest
    name: Fontship
    steps:
      - name: Fontship make variable-woff2
        id: fontship
        uses: theleagueof/fontship@v0.8.2
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.fontship.outputs.DISTDIR }}
          path: ${{ steps.fontship.outputs.DISTDIR }}.zip
